// Flower data, quiz paths, questions, lore — TH + EN
// Keep it modest: enough to feel real, not bloated.

const FLOWERS = {
  jasmine: {
    en: "Jasmine",
    th: "มะลิ",
    tagline_en: "Quiet devotion",
    tagline_th: "ใจที่อ่อนโยน",
    lore_en: "Worn by Thai mothers, jasmine is the scent of pure love. It blooms at night and gives itself away by morning.",
    lore_th: "ดอกมะลิเป็นกลิ่นของความรักบริสุทธิ์ บานในเวลากลางคืน และร่วงโรยตอนรุ่งเช้า",
    fortune_en: "Today, the people who love you are thinking of you. Reply to that message.",
    fortune_th: "วันนี้คนที่รักคุณกำลังคิดถึงคุณอยู่ — ตอบข้อความเค้าสักนิดนะ",
    pair_en: "Bergamot tea, white linen, your mum's voice",
    pair_th: "ชามะกรูด, ผ้าลินิน, เสียงแม่",
    hex: "#fdf6e3",
    petal: "#fffdf6",
    center: "#e8c97a",
    shape: "cluster",
    tone: { deep: "#e8c97a", mid: "#fffaf0", light: "#fffdf2", edge: "#fffdf6" },
  },
  peony: {
    en: "Peony",
    th: "โบตั๋น",
    tagline_en: "Big feelings, soft delivery",
    tagline_th: "หัวใจฟูฟ่อง",
    lore_en: "The peony is a romantic with poker face. It blooms enormously for one short week and then it's over.",
    lore_th: "โบตั๋นบานใหญ่เพียงสัปดาห์เดียว — สวยแบบเขินๆ แต่จัดเต็มทุกกลีบ",
    fortune_en: "You are allowed to take up space this week. Bloom loudly.",
    fortune_th: "สัปดาห์นี้คุณมีสิทธิ์เด่นได้ ไม่ต้องเก็บตัว",
    pair_en: "Strawberry milk, slow Sundays, kdrama tears",
    pair_th: "นมสตรอว์เบอร์รี, วันอาทิตย์เนิบๆ, ซีรีส์เกาหลีน้ำตาไหล",
    hex: "#fbe4ec",
    petal: "#f5b8cf",
    center: "#c97a9b",
    shape: "ruffle",
    tone: { deep: "#d97aa0", mid: "#f5b8cf", light: "#fde2ec", edge: "#fff0f5" },
  },
  sunflower: {
    en: "Sunflower",
    th: "ทานตะวัน",
    tagline_en: "Faces the light, always",
    tagline_th: "หันหาแสงเสมอ",
    lore_en: "Sunflowers follow the sun even on cloudy days. You can be this stubborn about your own joy.",
    lore_th: "ทานตะวันหันหน้าตามแสงทุกวัน — คุณก็ดื้อกับความสุขของตัวเองได้นะ",
    fortune_en: "Say yes to the small invitation. It's bigger than it looks.",
    fortune_th: "ตอบรับคำชวนเล็กๆ ของวันนี้ — มันใหญ่กว่าที่คิด",
    pair_en: "Iced cocoa, denim, your loudest playlist",
    pair_th: "โกโก้เย็น, ยีนส์ตัวเก่ง, เพลย์ลิสต์เสียงดัง",
    hex: "#fff4c2",
    petal: "#f5c542",
    center: "#7a4a1a",
    shape: "ray",
    tone: { deep: "#7a4a1a", mid: "#f5c542", light: "#fff4c2", edge: "#fffae0" },
  },
  ranunculus: {
    en: "Ranunculus",
    th: "รานันคูลัส",
    tagline_en: "You are charming and you know it",
    tagline_th: "เสน่ห์ล้น ตัวเองยังรู้",
    lore_en: "A hundred tissue-thin petals stacked into one tiny bloom. Pure dopamine in flower form.",
    lore_th: "กลีบบางเฉียบเป็นร้อยกลีบในดอกเดียว — โดปามีนรูปดอกไม้",
    fortune_en: "A small kindness from you will rearrange someone's whole week.",
    fortune_th: "ความใจดีเล็กๆ ของคุณจะเปลี่ยนทั้งสัปดาห์ของใครบางคน",
    pair_en: "Champagne, dancing in socks, late texts",
    pair_th: "ไวน์ฟอง, เต้นในถุงเท้า, แชตดึกๆ",
    hex: "#fde7d8",
    petal: "#f0a875",
    center: "#c46a3a",
    shape: "ruffle",
    tone: { deep: "#c46a3a", mid: "#f0a875", light: "#fde7d8", edge: "#fff3e8" },
  },
  anemone: {
    en: "Anemone",
    th: "อะนีโมเน่",
    tagline_en: "Tender and a little goth",
    tagline_th: "อ่อนโยนแบบมีมุมมืด",
    lore_en: "Black-hearted but soft-petalled. Anemone says: you can hold both at once.",
    lore_th: "ตรงกลางสีดำสนิท กลีบนุ่มเป็นแพร — ความอ่อนโยนกับความมืดอยู่ในดอกเดียวกันได้",
    fortune_en: "Rest is the plot twist. Take the nap.",
    fortune_th: "พักผ่อนคือทางออก — งีบไปเลยนะ",
    pair_en: "Black coffee, vintage cardigans, rain on glass",
    pair_th: "กาแฟดำ, เสื้อคาร์ดิแกนเก่า, เสียงฝนบนกระจก",
    hex: "#e8dff5",
    petal: "#cdbde8",
    center: "#1a1426",
    shape: "single",
    tone: { deep: "#1a1426", mid: "#cdbde8", light: "#e8dff5", edge: "#f5eefb" },
  },
  lotus: {
    en: "Lotus",
    th: "บัวหลวง",
    tagline_en: "Rooted in mud, blooming anyway",
    tagline_th: "งอกจากโคลน แต่บานสะอาด",
    lore_en: "The lotus closes at night and opens at dawn. A new chance every morning, written into the plant.",
    lore_th: "บัวหุบในคืน เปิดในรุ่งเช้า — โอกาสใหม่ทุกวัน เขียนไว้ในกลีบ",
    fortune_en: "Forgive yourself for last week. This one is a fresh page.",
    fortune_th: "ให้อภัยตัวเองสำหรับสัปดาห์ที่แล้ว — สัปดาห์นี้คือหน้าใหม่",
    pair_en: "Morning temple bells, jasmine rice, deep breath",
    pair_th: "เสียงระฆังเช้า, ข้าวหอมมะลิ, ลมหายใจลึกๆ",
    hex: "#f9e3ee",
    petal: "#f5b8cf",
    center: "#e8c97a",
    shape: "lotus",
    tone: { deep: "#d97aa0", mid: "#f5b8cf", light: "#fde2ee", edge: "#fff0f5" },
  },
  iris: {
    en: "Iris",
    th: "ไอริส",
    tagline_en: "Messenger of good news",
    tagline_th: "ผู้ส่งข่าวดี",
    lore_en: "Iris was a goddess who rode rainbows between worlds. Her flower carries messages you didn't know you needed.",
    lore_th: "เทพีไอริสขี่สายรุ้งส่งข่าว — ดอกของเธอนำข่าวที่คุณรอ",
    fortune_en: "Write the message you've been drafting. Send it today.",
    fortune_th: "ข้อความที่ค้างใน draft อยู่ — กดส่งวันนี้เลย",
    pair_en: "Lavender soap, handwritten cards, blue hour walks",
    pair_th: "สบู่ลาเวนเดอร์, การ์ดเขียนมือ, เดินตอนพลบค่ำ",
    hex: "#d8d4f0",
    petal: "#7a6dc7",
    center: "#f5c542",
    shape: "iris",
    tone: { deep: "#5a4ba8", mid: "#7a6dc7", light: "#d8d4f0", edge: "#ede9fa" },
  },
  marigold: {
    en: "Marigold",
    th: "ดาวเรือง",
    tagline_en: "Loud, golden, lucky",
    tagline_th: "เหลืองอร่าม นำโชค",
    lore_en: "Marigold guards thresholds and welcomes back what was lost. Wear it when you need to be found.",
    lore_th: "ดาวเรืองเฝ้าประตู เรียกของหายให้กลับมา — ใส่ไว้เมื่ออยากให้ใครหาเจอ",
    fortune_en: "Wear something gold. Be impossible to miss.",
    fortune_th: "ใส่ของสีทองสักชิ้น — ให้คนหาคุณเจอง่ายๆ",
    pair_en: "Sticky rice, temple visits, gold jewellery",
    pair_th: "ข้าวเหนียว, ไปทำบุญ, ทองเส้นเล็กๆ",
    hex: "#fff0c4",
    petal: "#f5a623",
    center: "#c46a1a",
    shape: "ray",
    tone: { deep: "#c46a1a", mid: "#f5a623", light: "#fff0c4", edge: "#fff8d8" },
  },
};

const FLOWER_KEYS = Object.keys(FLOWERS);

// Reading paths — secular only (no astrology / horoscope)
const PATHS = [
  { id: "mood",       icon: "○", en: "Today's Mood",     th: "อารมณ์วันนี้",   sub_en: "Quick 3-Q check-in",        sub_th: "เช็คใจ 3 ข้อ" },
  { id: "love",       icon: "♡", en: "Love Status",      th: "สถานะหัวใจ",     sub_en: "Where's your heart this week?", sub_th: "หัวใจคุณอยู่ตรงไหน" },
  { id: "quiz",       icon: "✧", en: "Personality Quiz", th: "ควิซบุคลิก",     sub_en: "Which bloom matches you",   sub_th: "ดอกไหนเข้ากับนิสัย" },
  { id: "birthmonth", icon: "✿", en: "Birth Month",      th: "เดือนเกิด",      sub_en: "Your Victorian birth flower", sub_th: "ดอกไม้ประจำเดือนเกิด" },
  { id: "occasion",   icon: "✦", en: "By Occasion",      th: "ตามโอกาส",       sub_en: "Gift, sorry, thank you, congrats", sub_th: "ของขวัญ ขอโทษ ขอบคุณ ยินดี" },
];

// One short quiz of 3 questions, with options each tied to a flower.
// Same questions across paths (with subtle reframing) — keeps build tight.
const QUIZ = [
  {
    en: "Pick a Sunday morning",
    th: "เลือกเช้าวันอาทิตย์",
    options: [
      { en: "Slow coffee, no plans",        th: "กาแฟช้าๆ ไม่มีแพลน",       flower: "anemone" },
      { en: "Market run, fresh bread",       th: "ไปตลาด ซื้อขนมปังร้อนๆ",   flower: "marigold" },
      { en: "Lying in the sun like a cat",   th: "นอนตากแดดเหมือนแมว",        flower: "sunflower" },
      { en: "Crying at a kdrama",            th: "ร้องไห้กับซีรีส์เกาหลี",    flower: "peony" },
    ],
  },
  {
    en: "Your love language is…",
    th: "ภาษารักของคุณคือ…",
    options: [
      { en: "Tiny daily texts",              th: "ข้อความสั้นๆ ทุกวัน",        flower: "jasmine" },
      { en: "Cooking for them",              th: "ทำอาหารให้กิน",              flower: "lotus" },
      { en: "Big dramatic gestures",         th: "โชว์ใหญ่ๆ แบบหนังรัก",       flower: "peony" },
      { en: "Sitting in silence together",   th: "นั่งเงียบๆ ด้วยกันได้",      flower: "anemone" },
    ],
  },
  {
    en: "I want this week to feel…",
    th: "อยากให้สัปดาห์นี้รู้สึก…",
    options: [
      { en: "Lucky",                         th: "โชคดี",                       flower: "marigold" },
      { en: "Held",                          th: "อบอุ่น มีคนโอบ",             flower: "jasmine" },
      { en: "Bright",                        th: "สดใส",                        flower: "sunflower" },
      { en: "Soft",                          th: "นุ่มนวล",                     flower: "ranunculus" },
    ],
  },
];

// Thai day-of-week colors (Sunday → Saturday)
const THAI_DAYS = [
  { en: "Sunday",    th: "อาทิตย์", color: "#e8504a", short: "SUN", flower: "marigold" },
  { en: "Monday",    th: "จันทร์",  color: "#f5c542", short: "MON", flower: "jasmine" },
  { en: "Tuesday",   th: "อังคาร",  color: "#f5b8cf", short: "TUE", flower: "peony" },
  { en: "Wednesday", th: "พุธ",     color: "#7fb069", short: "WED", flower: "lotus" },
  { en: "Thursday",  th: "พฤหัส",   color: "#f0a875", short: "THU", flower: "ranunculus" },
  { en: "Friday",    th: "ศุกร์",   color: "#7a9fd8", short: "FRI", flower: "iris" },
  { en: "Saturday",  th: "เสาร์",   color: "#9a7ec7", short: "SAT", flower: "anemone" },
];

const ZODIACS = [
  { en: "Aries",       th: "ราศีเมษ",      glyph: "♈", flower: "sunflower" },
  { en: "Taurus",      th: "ราศีพฤษภ",     glyph: "♉", flower: "peony" },
  { en: "Gemini",      th: "ราศีเมถุน",    glyph: "♊", flower: "ranunculus" },
  { en: "Cancer",      th: "ราศีกรกฎ",     glyph: "♋", flower: "jasmine" },
  { en: "Leo",         th: "ราศีสิงห์",    glyph: "♌", flower: "marigold" },
  { en: "Virgo",       th: "ราศีกันย์",    glyph: "♍", flower: "lotus" },
  { en: "Libra",       th: "ราศีตุล",      glyph: "♎", flower: "iris" },
  { en: "Scorpio",     th: "ราศีพิจิก",    glyph: "♏", flower: "anemone" },
  { en: "Sagittarius", th: "ราศีธนู",      glyph: "♐", flower: "sunflower" },
  { en: "Capricorn",   th: "ราศีมังกร",   glyph: "♑", flower: "lotus" },
  { en: "Aquarius",    th: "ราศีกุมภ์",    glyph: "♒", flower: "iris" },
  { en: "Pisces",      th: "ราศีมีน",      glyph: "♓", flower: "ranunculus" },
];

// Bouquets / jars / posies / dried — products to offer
const PRODUCTS = {
  bouquet: {
    en: "The Full Bouquet",
    th: "ช่อใหญ่",
    sub_en: "Hand-tied, 18–22 stems",
    sub_th: "มัดมือ 18–22 ก้าน",
    price: 1290,
  },
  jar: {
    en: "Flower Jar",
    th: "โหลดอกไม้",
    sub_en: "Glass jar arrangement, fresh weekly",
    sub_th: "จัดในโหลแก้ว เปลี่ยนทุกสัปดาห์",
    price: 890,
  },
  posy: {
    en: "Mini Posy",
    th: "ช่อเล็ก",
    sub_en: "Pocket-sized, 7 stems",
    sub_th: "ช่อจิ๋ว 7 ก้าน",
    price: 450,
  },
  dried: {
    en: "Dried Keepsake",
    th: "ดอกไม้แห้ง",
    sub_en: "Lasts a year, hung upside-down",
    sub_th: "เก็บได้ทั้งปี ห้อยหัวลง",
    price: 690,
  },
};

Object.assign(window, { FLOWERS, FLOWER_KEYS, PATHS, QUIZ, THAI_DAYS, ZODIACS, PRODUCTS });
